# Generated by Django 3.0.5 on 2020-04-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raashan_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='cnic',
            field=models.CharField(db_index=True, max_length=13, verbose_name='CNIC'),
        ),
    ]
